### ISSUE TITLE
如何支持文字+表情的显示

### ISSUE THREAD

**Issue by zhuyz89** [Bilibili/DanmakuFlameMaster#106]
请问，目前是否支持文字+表情的显示？该如何设置？

**Comment by ctiao** [comment]
看Sample

**Comment by ctiao** [comment]
如果你需要预先创建好图文的占位符，在显示的时候加载图片，看一下这个方法
http://developer.android.com/reference/android/text/Html.html#fromHtml(java.lang.String, android.text.Html.ImageGetter, android.text.Html.TagHandler)

**Comment by zhuyz89** [comment]
本来打算用SpannableString实现的，但是看了里面的实现方式，最后是使用了canvas.drawText实现的，canvas.drawText里面最后会把SpannableString转成了String，所以SpannableString的格式都不生效了，显示的还是字符串。用fromHtml还是看，但这个表情多个的时候比较麻烦吧，Sample里面好像并没有显示表情的列子吧？

**Comment by zhuyz89** [comment]
哦，看到了，好像是前不久更新的，我忘记更新了，我试试先，O(∩_∩)O谢谢
