### ISSUE TITLE
使用DanmakuSurfaceView来绘制弹幕，弹幕总是在屏幕的最上方

### ISSUE THREAD

**Issue by brucetoo** [Bilibili/DanmakuFlameMaster#108]
试过用 类似于像 视频处理的 SurfaceView 中使用 
        setFocusable(true);
        setFocusableInTouchMode(true);
        requestFocus(); 
来解决，但是还是没效果，请问有什么方法可以让弹幕绘制的layer层（DanmakuSurfaceView）和能在
FrameLayout里面体现出跟普通view一样的层级效果

**Comment by xqq** [comment]
用 DanmakuView 吧。
而且 DanmakuSurfaceView 的绘制没有硬件加速

**Comment by brucetoo** [comment]
现在主要是Cut了 parser相关的很多代码，就用DanmakuSurfaceView代替了，于是出现了这种问题，请问能有什么方法解决这个？

**Comment by xqq** [comment]
SurfaceView 的特性好像就是这样。不过为什么不用 DanmakuView 呢？这与 parser 无关的。

**Comment by brucetoo** [comment]
恩恩 我试试。但是视频播放的view也是从SurfaceView中继承的，都可以控制其在FrameLayout中得位置。。好神奇。。。

**Comment by brucetoo** [comment]
我想问问 DanmakuSurfaceView 这个 DanmakuView 对比性能方面有什么影响？ 为什么推荐使用DanmakuView 但是又要写一个DanmakuSurfaceView

**Comment by xqq** [comment]
SurfaceView 虽说号称高效率的双缓冲绘制，但是它的 SurfaceHolder.lockCanvas() 出来的 Canvas 是纯软件渲染的，实际效率比系统 View 的 Canvas 差一大截。

**Comment by xqq** [comment]
DanmakuSurfaceView 是早期写的

**Comment by brucetoo** [comment]
好的，谢谢您的回答
