### ISSUE TITLE
此lib在较为低端的上会卡。

### ISSUE THREAD

**Issue by brucetoo** [Bilibili/DanmakuFlameMaster#114]
大致情况是 弹幕和一般普通动画同时执行时，弹幕会卡停一下，机型大致为 1G ram 内存的手机。。有没有一些解决方案啊？

**Comment by xqq** [comment]
应该是卡了主线程... 用 DanmakuSurfaceView?

**Comment by brucetoo** [comment]
恩恩 是用个这个DanmakuSurfaceView  就是卡了主线程

**Comment by xqq** [comment]
DanmakuSurfaceView 照理不会啊，这是在独立线程绘制的。
DanmakuView 倒确实是在主线程绘制的。

**Comment by brucetoo** [comment]
DanmakuSurfaceView 和 DanmakuView  我都试过了。。效果不明显，有什么具体的解决方案什么的吗？卡得真有点恶心

**Comment by ctiao** [comment]
什么cpu和gpu的设备？   跟ram关系不大

**Comment by brucetoo** [comment]
这个太杂了。。。大部分是什么 联想 华为的机型

**Comment by ctiao** [comment]
如果是3.0以上(api >= 11) 系统，可以使用DanmakuView并开启图形硬件加速，但是对低配机器估计也不会有多少提升。   造成卡的感觉的瓶颈一般都在绘制效率和稳定性， 你可以测试绘一屏大小的bitmap  需要多少毫秒，如果绘制一屏时间超过25毫秒，那估计怎么优化也没什么卵用

**Comment by brucetoo** [comment]
其实说的都有试过了。。还是没什么卵用。。应该是其他动画太多得原因。正在改。。。谢谢
