### ISSUE TITLE
在绘制弹幕时，弹幕会出现闪动、模糊的现象。如何改变绘制时间，demo的试了，效果不明显

### ISSUE THREAD

**Issue by 10045125** [Bilibili/DanmakuFlameMaster#116]
1.绘制弹幕是，是采用线程休眠的方式去控制帧数还是通过其他方式？
2.控制弹幕绘制时间有哪些方式呢？
3.绘制弹幕是会出现卡顿和模糊。
4.我使用的是DanmakuView。

斗鱼也是用这个库，但客户端弹幕表现很差，晃动特别严重。

**Comment by ctiao** [comment]
1.如果绘制过快是通过休眠来控制，绘制慢的话基本不会休眠
2.绘制时间是指什么？  
3.模糊是什么？  看看demo下方的cache miss是否一直增加     另外设备gpu性能如何
4.是否开启硬件加速
斗鱼的库是很老的版本

**Comment by 10045125** [comment]
1.绘制时间是在屏幕显示的时间
  BaseDanmaku danmaku = DanmakuFactory.createDanmaku(BaseDanmaku.TYPE_SCROLL_RL, mAndroidDisplayer);
danmaku.time 是这个设置屏幕弹幕的绘制时间？
2.模糊是弹幕在屏幕显示的时候文字 会出现视觉残留，让人感觉文字有模糊现象。
3.设备是三星的S6
4.APP我启用了全局的硬件加速 android:hardwareAccelerated="true"

**Comment by 10045125** [comment]
我之前写跑马灯的时候，就发现如果绘制帧数不够会出现丢帧，也会导致卡顿，我看了里面的源码，是不是通过这个控制帧数
  private void updateInNewThread() {
        if (mThread != null) {
            return;
        }
        mThread = new UpdateThread("DFM Update") {
            @Override
            public void run() {
                long lastTime = System.currentTimeMillis();
                long dTime = 0;
                while (!isQuited() && !quitFlag) {
                    long startMS = System.currentTimeMillis();
                    dTime = System.currentTimeMillis() - lastTime;
                    long diffTime = mFrameUpdateRate - dTime;
                    if (diffTime > 1) {
                        SystemClock.sleep(1);
                        continue;
                    }
                    lastTime = startMS;
                    long d = syncTimer(startMS);
                    if (d < 0) {
                        SystemClock.sleep(60 - d);
                        continue;
                    }
                    d = mDanmakuView.drawDanmakus();
                    if (!mDanmakusVisible) {
                        waitRendering(INDEFINITE_TIME);
                    } else if (mRenderingState.nothingRendered && mIdleSleep) {
                        dTime = mRenderingState.endTime - timer.currMillisecond;
                        if (dTime > 500) {
                            notifyRendering();
                            waitRendering(dTime - 400);
                        }
                    }
                }
            }
        };
        mThread.start();
    }

**Comment by 10045125** [comment]
你好，请问下如何控制弹幕的滚动速度，比如像bilili android客户端那样看起来比较慢会比较舒服。

**Comment by 10045125** [comment]
看了源码，需要设置 DanmakuGlobalConfig 里面的滚动系数。
 /**
     * 默认滚动速度系数
     */
    public float scrollSpeedFactor = 1.0f;


    /**
     * 绘制刷新率(毫秒)
     */
    public int refreshRateMS = 15;

**Comment by ctiao** [comment]
使用DanmakuGlobalConfig.DEFAULT.setScrollSpeedFactor方法设置
