### ISSUE TITLE
描边和阴影设置问题

### ISSUE THREAD

**Issue by 10045125** [Bilibili/DanmakuFlameMaster#118]
请问下，bilibili弹幕设置里面的   描边/阴影大小   如何去设置。

 DanmakuGlobalConfig.DEFAULT.setDanmakuStyle() 是这个么，但我试过了，貌似木有效果。期待你的回复，thanks。

**Comment by ctiao** [comment]
danmaku.textShadowColor不能是透明颜色
setDanmakuStyle(   设置第二个数值参数
