### ISSUE TITLE
Demo中留有使用JSON解析的方式，但是跑起来实际没有效果？这块是ok的？还是说有规则和约束？多谢！

### ISSUE THREAD

**Issue by fuminwen** [Bilibili/DanmakuFlameMaster#119]
现在B站用xml获取内容，json的方案是否已经有可行？

**Comment by ctiao** [comment]
json格式文件在 https://github.com/Bilibili/DanmakuFlameMaster/tree/master/Sample/src/main/assets
需要使用特定的parser，parser在https://github.com/Bilibili/DanmakuFlameMaster/blob/a444e0ff6e857ea210b46b2215ad5d0decb8b6e4/DanmakuFlameMaster/src/main/java/master/flame/danmaku/danmaku/parser/android/AcFunDanmakuParser.java

**Comment by Weststreet** [comment]
Json parser有错误

**Comment by ctiao** [comment]
https://github.com/Bilibili/DanmakuFlameMaster/commit/245d1387c66c2c5d888fd9e288422acda04a82dd
已经修复。
