### ISSUE TITLE
ConcurrentModificationException错误

### ISSUE THREAD

**Issue by scottguosk** [Bilibili/DanmakuFlameMaster#120]
我使用的版本是v0.3.2，出现了下面的问题，请帮忙看看

07-17 11:03:37.560: W/System.err(14862): java.util.ConcurrentModificationException
07-17 11:03:37.560: W/System.err(14862): 	at java.util.TreeMap$MapIterator.stepForward(TreeMap.java:883)
07-17 11:03:37.560: W/System.err(14862): 	at java.util.TreeMap$BoundedMap$BoundedIterator.stepForward(TreeMap.java:1485)
07-17 11:03:37.560: W/System.err(14862): 	at java.util.TreeMap$BoundedMap$BoundedEntrySet$1.next(TreeMap.java:1513)
07-17 11:03:37.560: W/System.err(14862): 	at java.util.TreeMap$BoundedMap$BoundedEntrySet$1.next(TreeMap.java:1511)
07-17 11:03:37.560: W/System.err(14862): 	at java.util.TreeMap.count(TreeMap.java:1656)
07-17 11:03:37.560: W/System.err(14862): 	at java.util.TreeMap$BoundedMap.size(TreeMap.java:1126)
07-17 11:03:37.568: W/System.err(14862): 	at java.util.TreeSet.size(TreeSet.java:256)
07-17 11:03:37.568: W/System.err(14862): 	at java.util.LinkedList.addAll(LinkedList.java:386)
07-17 11:03:37.568: W/System.err(14862): 	at java.util.LinkedList.<init>(LinkedList.java:261)
07-17 11:03:37.568: W/System.err(14862): 	at master.flame.danmaku.danmaku.model.android.Danmakus.a(Danmakus.java:184)
07-17 11:03:37.568: W/System.err(14862): 	at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler.a(CacheManagingDrawTask.java:561)
07-17 11:03:37.568: W/System.err(14862): 	at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler.handleMessage(CacheManagingDrawTask.java:445)
07-17 11:03:37.568: W/System.err(14862): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-17 11:03:37.576: W/System.err(14862): 	at android.os.Looper.loop(Looper.java:137)
07-17 11:03:37.576: W/System.err(14862): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by loveyanbei** [comment]
看起来需要换个concurrentMap来做这个工作

**Comment by scottguosk** [comment]
package master.flame.danmaku.danmaku.model.android;  

  @Override
    public IDanmakus subnew(long startTime, long endTime) {
        Collection<BaseDanmaku> subset = subset(startTime, endTime);
        if (subset == null) {
            return null;
        }
        ArrayList<BaseDanmaku> newSet = new ArrayList<BaseDanmaku>(subset);
        return new Danmakus(newSet);
    }

这个函数的ArrayList<BaseDanmaku> newSet = new ArrayList<BaseDanmaku>(subset);一直出现这个问题

**Comment by ctiao** [comment]
使用master上最新版本

**Comment by zhjunliu** [comment]
最新版本还是有这个问题
java.util.ConcurrentModificationException
	at java.util.TreeMap$MapIterator.stepForward(TreeMap.java:883)
	at java.util.TreeMap$BoundedMap$BoundedIterator.stepForward(TreeMap.java:1485)
	at java.util.TreeMap$BoundedMap$BoundedEntrySet$1.next(TreeMap.java:1513)
	at java.util.TreeMap$BoundedMap$BoundedEntrySet$1.next(TreeMap.java:1511)
	at java.util.TreeMap.count(TreeMap.java:1656)
	at java.util.TreeMap$BoundedMap.size(TreeMap.java:1126)
	at java.util.TreeSet.size(TreeSet.java:256)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:339)
	at java.util.ArrayList.<init>(ArrayList.java:93)
	at master.flame.danmaku.b.b.a.d.a(Danmakus.java:184)
	at master.flame.danmaku.a.a$a$a.a(CacheManagingDrawTask.java:558)
	at master.flame.danmaku.a.a$a$a.handleMessage(CacheManagingDrawTask.java:442)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by ctiao** [comment]
57fbaa5b251d835fc6aaf1795c59f5612cb92695
用比较暴力的方法解决了，在缓存线程try/catch  ，因为这么解决不会影响绘制线程所以不是问题很大.
