### ISSUE TITLE
弹幕在M版本上挂了,so中的错误，望兼容下

### ISSUE THREAD

**Issue by brucetoo** [Bilibili/DanmakuFlameMaster#122]

**Comment by brucetoo** [comment]
08-11 17:37:40.639      369-369/? A/DEBUG﹕ #00 pc 00001198  /data/app/com.netease.cc-1/lib/arm/libndkbitmap.so (Java_tv_cjump_jni_NativeBitmapFactory_release+15)
08-11 17:37:40.640      369-369/? A/DEBUG﹕ #01 pc 01460c95  /data/app/com.netease.cc-1/oat/arm/base.odex (boolean tv.cjump.jni.NativeBitmapFactory.release()+72)
08-11 17:37:40.640      369-369/? A/DEBUG﹕ #02 pc 01460883  /data/app/com.netease.cc-1/oat/arm/base.odex (void tv.cjump.jni.NativeBitmapFactory.loadLibs()+590)
08-11 17:37:40.640      369-369/? A/DEBUG﹕ #03 pc 01ac66af  /data/app/com.netease.cc-1/oat/arm/base.odex (void master.flame.danmaku.controller.CacheManagingDrawTask.<init>(master.flame.danmaku.danmaku.model.DanmakuTimer, android.content.Context, master.flame.danmaku.danmaku.model.AbsDisplayer, master.flame.danmaku.controller.IDrawTask$TaskListener, int)+242)
08-11 17:37:40.640      369-369/? A/DEBUG﹕ #04 pc 0140e0d1  /data/app/com.netease.cc-1/oat/arm/base.odex (master.flame.danmaku.controller.IDrawTask master.flame.danmaku.controller.DrawHandler.createDrawTask(boolean, master.flame.danmaku.danmaku.model.DanmakuTimer, android.content.Context, int, int, boolean, master.flame.danmaku.controller.IDrawTask$TaskListener)+748)
08-11 17:37:40.640      369-369/? A/DEBUG﹕ #05 pc 0140ea27  /data/app/com.netease.cc-1/oat/arm/base.odex (void master.flame.danmaku.controller.DrawHandler.prepare(java.lang.Runnable)+394)
08-11 17:37:40.640      369-369/? A/DEBUG﹕ #06 pc 014103e5  /data/app/com.netease.cc-1/oat/arm/base.odex (void master.flame.danmaku.controller.DrawHandler.handleMessage(android.os.Message)+344)
08-11 17:37:40.640      369-369/? A/DEBUG﹕ #07 pc 734ef1c9  /data/dalvik-cache/arm/system@framework@boot.oat

**Comment by ctiao** [comment]
DFM是什么版本

**Comment by brucetoo** [comment]
我改的比较杂，好像不是最新的，大概3个月前的最新版本，so有更新过 ？ 或者你们有做M版的兼容是什么时候？

**Comment by ctiao** [comment]
https://github.com/Bilibili/NativeBitmapFactory/commit/eef49fe4937615aae0e1318b9d67dc5bcd3ef0ec
有更新过native库, 用最新的so文件替换进去测试，或者更新到最新版本。

**Comment by brucetoo** [comment]
换了so 其他的地方java代码有做过什么相应的改动吗？

**Comment by ctiao** [comment]
NativeBitmapFactory 也要看下有没有改动，忘记有没有更新了

**Comment by brucetoo** [comment]
感谢总是那么及时的回复！谢谢~~ 替换SO解决问题了

**Comment by xqq** [comment]
目前应该是暂时不兼容M。最新的代码在Native下检测到符号不全就不加载了，会自动禁用NDKBitmap。

M镜像刚出的时候没有正式的m源代码放出来，因此暂时不太好做兼容，暂时先禁掉

**Comment by androidwifi** [comment]
什么时候支持6.0版本呢, 毕竟现在升级到6.0的手机越来越多了...

**Comment by brucetoo** [comment]
用最新的so 不会有问题耶  我原生6.0系统不会有问题

**Comment by androidwifi** [comment]
@brucetoo , Nexus5+6.0 上替换完最新的so库不再crash, 谢谢~
