### ISSUE TITLE
how to control the danmaku density

### ISSUE THREAD

**Issue by leonard0629** [Bilibili/DanmakuFlameMaster#124]
as you said, if i want to use DanmakuGlobalConfig.setMaximumVisibleSizeInScreen, i should not use set the priority of BaseDanmaku. But when i comment it, the danmaku is gone. how can i make them visible and also can use DanmakuGlobalConfig.setMaximumVisibleSizeInScreen?
```
BaseDanmaku danmaku = DanmakuFactory.createDanmaku(getDanmakuType());
            danmaku.text = barrage.getContent();
            danmaku.padding = 5;
            //danmaku.priority = 1;
            danmaku.isLive = true;
            danmaku.textSize = 25f * (mParser.getDisplayer().getDensity() - 0.6f);
            danmaku.textColor = barrage.getColor();
            danmaku.borderColor = 0x0000000;
            danmaku.time = barrage.getTime()
            mDanmakuView.addDanmaku(danmaku);
```

**Comment by ctiao** [comment]
You should set the priority(> 0) of the Danmaku which was sent(commented) by yourself.

**Comment by leonard0629** [comment]
but i also want to use the DanmakuGlobalConfig.setMaximumVisibleSizeInScreen, as in issue#95 you said. https://github.com/Bilibili/DanmakuFlameMaster/issues/95.
"弹幕密度的意思是限制一屏最多能出现一定数量的弹幕，如果你addDanmaku的时候设置了弹幕的priority，会认为这条弹幕需要跳过过滤设置(见上链接)，这样就会使这条弹幕直接显示出来,使弹幕密度限制无效。
控制行数可以通过修改DanmakuView的高度达到目的,"
i'm confused

**Comment by ctiao** [comment]
A comment with priority (<=0) will always be filtered by filter. 
Cannot control if the comment would be filtered or not when priority<=0 with setMaximumVisibleSizeInScreen(n).

**Comment by leonard0629** [comment]
so you mean if i set the priority != 0 like danmaku.priority = 1, then i can use the setMaximumVisibleSizeInScreen(n) to control the density?

**Comment by ctiao** [comment]
设置了priority=1之后的弹幕，不会被密度限制，一定会显示出来。  
其他priority<=0的弹幕会被密度限制，可能会不显示，但是我们在运行之前没办法知道这条是否会被屏蔽现实。

**Comment by leonard0629** [comment]
well, let me in this way.
I get danmaku list from server, in my case, i want to control the setting of danmaku, such as textcolor, display position. so before setting, all danmaku shown and after setting, the danmaku which passed the filters will be shown

**Comment by leonard0629** [comment]
in your words, 
case priority = 1, all the danmaku will be shown
case priority <=0, the danmaku will not be shown
is that right?

**Comment by ctiao** [comment]
case priority = 1, all danmakus will be shown
case priority <=0, all danmakus **may be** filtered by the filters you registered 
setMaximumVisibleSizeInScreen is a filter too.

**Comment by leonard0629** [comment]
so if there are no filters danmakus with priority <= 0 will all be shown?

**Comment by ctiao** [comment]
yep

**Comment by leonard0629** [comment]
i tried, change from danmaku.priority = 1 to danmaku.priority = 0 and make the other codes still. but the danmakus never shown

**Comment by ctiao** [comment]
need more details or code

**Comment by ctiao** [comment]
danmaku.time = barrage.getTime()    

need more code especially "barrage.getTime()",

**Comment by leonard0629** [comment]
init danmakuview:
```
mDanmakuView = (IDanmakuView) findViewById(R.id.viewDanmaku);
        if (mDanmakuView != null) {
            mParser = createParser(null);
            mDanmakuView.setCallback(new DrawHandler.Callback() {

                @Override
                public void updateTimer(DanmakuTimer timer) {
                    //do nothing
                }

                @Override
                public void prepared() {
                    mDanmakuView.start();
                }
            });
            mDanmakuView.prepare(mParser);
            //showFPS true for debug
            mDanmakuView.showFPS(false);
            //enable drawing cache
            mDanmakuView.enableDanmakuDrawingCache(true);

            mDanmakuView.hide();
        }
```

**Comment by leonard0629** [comment]
add danmaku
```
BaseDanmaku danmaku = DanmakuFactory.createDanmaku(getDanmakuType());
            danmaku.text = barrage.getBarrage();
            danmaku.padding = 5;
            danmaku.isLive = true;
            danmaku.priority = 0;
            danmaku.textSize = 25f * (mParser.getDisplayer().getDensity() - 0.6f);
            danmaku.textColor = barrage.getColorValue();
            danmaku.textShadowColor = 0xFF000000;
            long videoTime = barrage.getVideoTime() * 1000;
            long currentTime = mVideoView.getCurrentPosition();
            long danmakuCurrentTime = mDanmakuView == null ? 0 : mDanmakuView.getCurrentTime();
            long time = videoTime - currentTime + danmakuCurrentTime;
            danmaku.time = time;
            mDanmakuView.addDanmaku(danmaku);
```

**Comment by leonard0629** [comment]
i don't think it's the time issue. because i just change the danmaku.priority from 0 to 1, all danmakus are shown

**Comment by ctiao** [comment]
may be filtered by some other filters.
can you output some logs in DanmakuFilters.java like below:
```
--- a/DanmakuFlameMaster/src/main/java/master/flame/danmaku/controller/DanmakuFilters.java
+++ b/DanmakuFlameMaster/src/main/java/master/flame/danmaku/controller/DanmakuFilters.java
@@ -476,6 +476,9 @@ public class DanmakuFilters {
             if (f != null) {
                 f.filter(danmaku, index, totalsizeInScreen, timer, fromCachingTask);
                 danmaku.filterResetFlag = GlobalFlagValues.FILTER_RESET_FLAG;
+                if (danmaku.isFiltered()) {
+                    //log out this danmaku and classname of f
+                }
             }
         }
     }
```

**Comment by leonard0629** [comment]
thx, solve my problem
