### ISSUE TITLE
question about setDanmakuStyle

### ISSUE THREAD

**Issue by leonard0629** [Bilibili/DanmakuFlameMaster#125]
```
DanmakuGlobalConfig.DEFAULT.setDanmakuStyle(DanmakuGlobalConfig.DANMAKU_STYLE_STROKEN, stokeWidth);
```
after use this i find this is not what i want. i want to make the danmaku text surround with black line not the square textview. what kind of style shall i use?

**Comment by leonard0629** [comment]
and how can i set the stoke color?

**Comment by ctiao** [comment]
use danmaku.textShadowColor = 0xf10000

**Comment by leonard0629** [comment]
and i use the right setting method?

**Comment by ctiao** [comment]
you should set textShadowColor color to each danmaku

**Comment by leonard0629** [comment]
```
DanmakuGlobalConfig.DEFAULT.setDanmakuStyle(DanmakuGlobalConfig.DANMAKU_STYLE_STROKEN, stokeWidth);
```
do i need to use this method to set the stoke width of textShadowColor?

**Comment by ctiao** [comment]
yes

**Comment by leonard0629** [comment]
```
danmaku.textShadowColor = 0x000000
```
i try to set the color black, but nothing change

**Comment by ctiao** [comment]
https://github.com/Bilibili/DanmakuFlameMaster/blob/master/Sample/src/main/java/com/sample/MainActivity.java#L151
you need to remove this line if you use my sample code. 
i disable stroke-drawing in the BackgroundCacheStuffer.drawStroke method

**Comment by leonard0629** [comment]
it works, thx
