### ISSUE TITLE
add danmaku

### ISSUE THREAD

**Issue by leonard0629** [Bilibili/DanmakuFlameMaster#126]
i met a question.
i load all posted danmaku at first and add them all into danmaku view when start video.
then i want to send a new danmaku to server and i add the danmku, but it didn't show. the history danmakus shown correctly. why this happen?

**Comment by leonard0629** [comment]
i do almost like the sample.
use a AsyncTask to add the history danmaku from server.
and as if i send a new danmaku, i call the timer.cancel, and add the danmaku to list, and restart the timer

**Comment by leonard0629** [comment]
maybe the danmaku time is wrong?
i set the time by call mVideoView.getCurrentPosition and i add a 2s delay

**Comment by ctiao** [comment]
did you create your danmaku-instance via DanmakuFactory.create(n) ?

**Comment by leonard0629** [comment]
yeah, of course
