### ISSUE TITLE
希望能增加一个模式，弹幕自动错开time防重叠（直播类app很需要）

### ISSUE THREAD

**Issue by DukeLee1989** [Bilibili/DanmakuFlameMaster#129]
希望能增加一个模式，弹幕自动错开time防重叠（直播类app很需要）

**Comment by YauzZ** [comment]
同问，有啥好思路没

**Comment by huohu1007** [comment]
请问这个问题解决了么，我也想解决这个问题

**Comment by gincoo** [comment]
mDanmakuContext  .preventOverlapping(null)//设置禁止重叠策略 null不限制
