### ISSUE TITLE
grade编译，so目录选择的问题

### ISSUE THREAD

**Issue by cikichen** [Bilibili/DanmakuFlameMaster#132]
通过grade直接依赖 `compile 'com.github.ctiao:dfm:0.3.5'`

但是我不想把库的armeabi这个目录也编译进去，应该怎么处理？

**Comment by ctiao** [comment]
defaultConfig里加
```
        ndk {
            abiFilters 'armeabi-v7a', 'x86', 'armeabi'
        }
```

保留想你想保留的目录

**Comment by cikichen** [comment]
Error:(36, 0) Error: NDK integration is deprecated in the current plugin.  Consider trying the new experimental plugin.  For details, see http://tools.android.com/tech-docs/new-build-system/gradle-experimental.  Set "android.useDeprecatedNdk=true" in gradle.properties to continue using the current NDK integration.

方法已经过时了，需要添加`android.useDeprecatedNdk=true`

**Comment by zhangxyfs** [comment]
没效果....我只想保留 armeabi-v7a
Error:Execution failed for task ':myvideo:transformNative_libsWithMergeJniLibsForLocalDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/x86/libndkbitmap.so
	File1: E:\develop\wopai-android\myvideo\build\intermediates\exploded-aar\com.github.ctiao\dfm\0.4.2\jni
	File2: E:\develop\wopai-android\myvideo\build\intermediates\exploded-aar\com.github.ctiao\DanmakuFlameMaster\0.4.9\jni
