### ISSUE TITLE
Android6.0不支持。。

### ISSUE THREAD

**Issue by clov4r-lyw** [Bilibili/DanmakuFlameMaster#135]
10-16 13:28:47.633: A/DEBUG(28026): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-16 13:28:47.633: A/DEBUG(28026): Build fingerprint: 'google/hammerhead/hammerhead:6.0/MRA58K/2256973:user/release-keys'
10-16 13:28:47.633: A/DEBUG(28026): Revision: '0'
10-16 13:28:47.634: A/DEBUG(28026): ABI: 'arm'
10-16 13:28:47.634: A/DEBUG(28026): pid: 29034, tid: 29249, name: DFM Handler Thr  >>> com.clov4r.android.nil <<<
10-16 13:28:47.634: A/DEBUG(28026): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x200005
10-16 13:28:47.650: A/DEBUG(28026):     r0 94ba4ca0  r1 9e86040c  r2 00430000  r3 aee96308
10-16 13:28:47.650: A/DEBUG(28026):     r4 9e189004  r5 00200005  r6 12d1e380  r7 12f50ca0
10-16 13:28:47.650: A/DEBUG(28026):     r8 12d1e380  r9 9f73be00  sl 9e8607ec  fp 00000000
10-16 13:28:47.650: A/DEBUG(28026):     ip 9e1861bd  sp 9e8603f0  lr a0babe0f  pc 9e1861cc  cpsr a00d0030
10-16 13:28:47.660: A/DEBUG(28026): backtrace:
10-16 13:28:47.660: A/DEBUG(28026):     #00 pc 000011cc  /data/app/com.clov4r.android.nil-2/lib/arm/libndkbitmap.so (Java_tv_cjump_jni_NativeBitmapFactory_release+15)
10-16 13:28:47.660: A/DEBUG(28026):     #01 pc 00efce0d  /data/app/com.clov4r.android.nil-2/oat/arm/base.odex (offset 0x828000) (boolean tv.cjump.jni.NativeBitmapFactory.release()+72)
10-16 13:28:47.660: A/DEBUG(28026):     #02 pc 00efca1b  /data/app/com.clov4r.android.nil-2/oat/arm/base.odex (offset 0x828000) (void tv.cjump.jni.NativeBitmapFactory.loadLibs()+510)
10-16 13:28:47.661: A/DEBUG(28026):     #03 pc 0130b13f  /data/app/com.clov4r.android.nil-2/oat/arm/base.odex (offset 0x828000) (void master.flame.danmaku.controller.CacheManagingDrawTask.<init>(master.flame.danmaku.danmaku.model.DanmakuTimer, android.content.Context, master.flame.danmaku.danmaku.model.AbsDisplayer, master.flame.danmaku.controller.IDrawTask$TaskListener, int)+242)
10-16 13:28:47.661: A/DEBUG(28026):     #04 pc 00e91b73  /data/app/com.clov4r.android.nil-2/oat/arm/base.odex (offset 0x828000) (master.flame.danmaku.controller.IDrawTask master.flame.danmaku.controller.DrawHandler.createDrawTask(boolean, master.flame.danmaku.danmaku.model.DanmakuTimer, android.content.Context, int, int, boolean, master.flame.danmaku.controller.IDrawTask$TaskListener)+766)
10-16 13:28:47.661: A/DEBUG(28026):     #05 pc 00e92547  /data/app/com.clov4r.android.nil-2/oat/arm/base.odex (offset 0x828000) (void master.flame.danmaku.controller.DrawHandler.prepare(java.lang.Runnable)+394)
10-16 13:28:47.661: A/DEBUG(28026):     #06 pc 00e93fa9  /data/app/com.clov4r.android.nil-2/oat/arm/base.odex (offset 0x828000) (void master.flame.danmaku.controller.DrawHandler.handleMessage(android.os.Message)+508)
10-16 13:28:47.661: A/DEBUG(28026):     #07 pc 736710c9  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x1eb1000)

**Comment by ctiao** [comment]
同 https://github.com/Bilibili/DanmakuFlameMaster/issues/122
升级最新的库代码

**Comment by clov4r-lyw** [comment]
@ctiao  好的，谢谢
