### ISSUE TITLE
DanmakuView.addDanmaku()在onCreate()中无效

### ISSUE THREAD

**Issue by whitecostume** [Bilibili/DanmakuFlameMaster#141]
因为要实现在Acitivity一打开就加载一些弹幕，在onCreate()中使用了DanmakuView.addDanmaku()添加几个弹幕，但没有显示，而我用一个Button测试，一下，用botton点击后就可以添加，请问是生命周期的问题吗

**Comment by ctiao** [comment]
DanmakuView isPrepared 并且view正确显示之后才可以添加弹幕

**Comment by frankiezz** [comment]
在isPrepared中加上mDanmakuView.start
