### ISSUE TITLE
用继承BaseDanmaku复写的Danmaku，要如何在DanmakuView里面实现点击监听

### ISSUE THREAD

**Issue by whitecostume** [Bilibili/DanmakuFlameMaster#149]
如题

**Comment by ctiao** [comment]
https://github.com/Bilibili/DanmakuFlameMaster/blob/master/Sample/src/main/java/com/sample/MainActivity.java#L189-L199

都是通过setOnDanmakuClickListener

**Comment by whitecostume** [comment]
感谢，已解决
