### ISSUE TITLE
弹幕抖动

### ISSUE THREAD

**Issue by mattxzhang** [Bilibili/DanmakuFlameMaster#169]
弹幕固定高度放在顶部，底部放EditText,键盘弹出和收起的时候，弹幕会停顿一下，5.0以下系统都有这个问题，是因为布局高度的改变造成重绘吗？

**Comment by ctiao** [comment]
是这个原因。
现在在高度或宽度其中一个改变的情况下都会重绘整屏弹幕，这部分可以进行细节调整优化： 在只是高度改变宽度不变的情况下，可以不进行重绘，可能导致的问题是会有部分已显示弹幕出屏

**Comment by mattxzhang** [comment]
能告诉下，在哪个类里面改么？我尝试一下

**Comment by mattxzhang** [comment]
刚试了下，屏蔽掉下面的代码还是不行
![image](https://cloud.githubusercontent.com/assets/8435870/12700092/4b8bd2ce-c80f-11e5-9e27-3ad7d34bee43.png)

**Comment by ctiao** [comment]
使用的是否是系统输入法？  请测试下其他输入法的弹出情况？

**Comment by mattxzhang** [comment]
用的百度输入法，估计不是弹幕的问题，可能是我页面的布局问题，目前5.0以下系统才有这个问题
