### ISSUE TITLE
smaple设置最大三行显示为两行

### ISSUE THREAD

**Issue by langive** [Bilibili/DanmakuFlameMaster#189]
// 设置最大显示行数
        HashMap<Integer, Integer> maxLinesPair = new HashMap<Integer, Integer>();
        maxLinesPair.put(BaseDanmaku.TYPE_SCROLL_RL, 3); // 滚动弹幕最大显示3行

       第一列显示为三行，其余都为两行

**Comment by ctiao** [comment]
fixed  88ceae356722f1b79e0dabf917cf052da17ae24e
