### ISSUE TITLE
pause() resume()和stop() start()对机器资源耗费差距大吗

### ISSUE THREAD

**Issue by shijia109** [Bilibili/DanmakuFlameMaster#218]
pause() resume()和stop() start()对机器资源耗费差距大吗，换句话说显示和隐藏弹幕调用那对方法比较好

**Comment by ctiao** [comment]
隐藏和显示调用hide()和show()好， 在hide状态会保持几百毫秒的休眠，其实跟完全退出线程性能差别不大
