### ISSUE TITLE
如何自定义弹幕数据，不采用json和xml方式

### ISSUE THREAD

**Issue by twolight** [Bilibili/DanmakuFlameMaster#236]
BaseDanmaku 如何设置属性。建议出一些开发文档

**Comment by twolight** [comment]
prepare(new BaseDanmakuParser(){
                @Override
                protected IDanmakus parse() {
                    return new Danmakus(createData(rates));
                }
            },mContext);


public BaseDanmaku createItem(Rate rate){
        String[] values = new String[]{"23.826000213623","1","25","16777215","1422201084"};

        long time = (long) (Float.parseFloat(values[0]) * 1000); // 出现时间
        int type = Integer.parseInt(values[1]); // 弹幕类型
        float textSize = Float.parseFloat(values[2]); // 字体大小
        int color = Integer.parseInt(values[3]) | 0xFF000000; // 颜色

        BaseDanmaku item = mContext.mDanmakuFactory.createDanmaku(type, mContext);
        if (item != null) {
            item.time = getCurrentTime() + 1000;
            item.textSize = textSize ;
            item.textColor = color;
            item.textShadowColor = color <= Color.BLACK ? Color.WHITE : Color.BLACK;
            item.text = rate.getContent();
        }
        return item;
    }
这样构造的弹幕显示出来

**Comment by AttackPangHu** [comment]
我也是自定义了解析器，但是也是不显示，请问你解决了吗
