### ISSUE TITLE
java.util.NoSuchElementException

### ISSUE THREAD

**Issue by qishi604** [Bilibili/DanmakuFlameMaster#247]
今天看了下友盟的崩溃日志，发现这个bug.
at java.util.LinkedList.getFirstImpl(LinkedList.java:538)
    at java.util.LinkedList.getFirst(LinkedList.java:530)

DrawHandler.java

```
private synchronized long getAverageRenderingTime() {
        int frames = mDrawTimes.size();
        if(frames <= 0)
            return 0;
        long dtime = mDrawTimes.getLast() - mDrawTimes.getFirst();
        return dtime / frames;
    }
```

synchronized作用于方法只能防止多个线程同时执行这个方法，并不能保证其他线程修改`mDrawTimes`这个变量。所以应该给`mDrawTimes`加锁

**Comment by yrom** [comment]
Yep you're right

**Comment by ctiao** [comment]
修复了的：https://github.com/Bilibili/DanmakuFlameMaster/commit/de0ac680c4fb304649911cc39cdfa4e344b69eec

升级版本
