### ISSUE TITLE
B站的xml弹幕文件在浏览器里显示正常，用下载工具下载后就会变成乱码

### ISSUE THREAD

**Issue by hienao** [Bilibili/DanmakuFlameMaster#271]
B站的xml弹幕文件在浏览器里显示正常，用下载工具下载后就会变成乱码，无法获取到xml的文件信息了，这是为什么呢？

**Comment by shiwentao666** [comment]
例如：http://comment.bilibili.com/6065590.xml

**Comment by kyriej** [comment]
因为b站弹幕量都是很大的，特意做了加压成二进制数据流，解析b站的弹幕时需要先解压
