### ISSUE TITLE
请问有屏蔽弹幕的示例代码吗，在Sample里面没有找到

### ISSUE THREAD

**Issue by blackbbc** [Bilibili/DanmakuFlameMaster#322]
如题 #298

**Comment by shenjingfs** [comment]
[DanmakuContext](https://github.com/Bilibili/DanmakuFlameMaster/blob/master/DanmakuFlameMaster/src/main/java/master/flame/danmaku/danmaku/model/android/DanmakuContext.java#L231)类里有相应方法
