### ISSUE TITLE
弹幕透明度问题

### ISSUE THREAD

**Issue by alvince** [Bilibili/DanmakuFlameMaster#355]
最新版本怎么实现像bilibili app一样播放中弹幕设置修改不透明度
没看到相关的api，demo感觉几百年没更新了一样😑

有没有指导方案

**Comment by alvince** [comment]
同上，像弹幕大小 密度 速度 等此类设置，播放中的弹幕如何修改

**Comment by alvince** [comment]
已解决
DanmakuContext配置及View属性

**Comment by allenZ7** [comment]
请问是怎么设置的呢，我调用setDanmakuTransparency 方法后，发现屏幕上的弹幕大部分是可以设置成功，但也有一两条是无效的或者说透明度还会更深

**Comment by alvince** [comment]
> 请问是怎么设置的呢，我调用setDanmakuTransparency 方法后，发现屏幕上的弹幕大部分是可以设置成功，但也有一两条是无效的或者说透明度还会更深

直接对视图修改alpha
