### ISSUE TITLE
图文混排，图片刷新不出来

### ISSUE THREAD

**Issue by 401885064** [Bilibili/DanmakuFlameMaster#360]
使用官方demo中MainActivity也一样，求解释？   debug知道线程已经把图片下载下来，drawable不为空，调用invalidateDanmaku方法，但屏幕上没有刷新图片

**Comment by 401885064** [comment]
谁能告诉下正确的使用姿势？？

**Comment by ctiao** [comment]
fixed  744e8f54bbffb8a441ca0ddbc5672d26dc1020c6
