### ISSUE TITLE
你一直都在攻击我。我说什么了？你自己有问题不知道吗？

### ISSUE THREAD

**Issue by ghost** [Bilibili/DanmakuFlameMaster#397]
你一直都在攻击我。我说什么了？你自己有问题不知道吗？

**Comment by ghost** [comment]
你自己说别人是这样想的。然后去攻击他。你幻想症啊。

**Comment by ghost** [comment]
luern0313  你自己人品这么有问题，你同事知道吗？

**Comment by luern0313** [comment]
b站把这个issue关掉吧，感谢

**Comment by luern0313** [comment]
已经没有聊下去的必要了

**Comment by xqq** [comment]
请不要污染 389 名 watcher 的邮箱。**开源项目 issue 区不是你公开泄粪的场所。**

**开源项目 issue 区不是你公开泄粪的场所。**

都已经是社会人了，行为举止连最基本的素质和礼貌都没有。**人间之屑**，你悔改罢

**Comment by luern0313** [comment]
对这么多watcher道个歉，很抱歉我的行为让你们的邮箱充满了垃圾样的邮件。
我在github并不想结识敌人，事情起因只是去解释问题，对这位老哥后来的一些言论很反感，由于本人有类似的经历，本想为了解决大家对自己软件的问题设立了一个软件讨论群，但后来时常有伸手党要求我做这个做那个，好像我做免费软件就有义务去解决他们的问题或者实现他们的需求，所以挺生气的。
这位老哥在之前issue中的言论是否正确已经无所谓了，毕竟我又不是程序或者产品，需求又不用我去实现。但如果真的想评价谁或言论，希望还是先把上一个issue看完。
再次抱歉。

**Comment by ghost** [comment]
> 对这么多watcher道个歉，很抱歉我的行为让你们的邮箱充满了垃圾样的邮件。
> 我在github并不想结识敌人，事情起因只是去解释问题，对这位老哥后来的一些言论很反感，由于本人有类似的经历，本想为了解决大家对自己软件的问题设立了一个软件讨论群，但后来时常有伸手党要求我做这个做那个，好像我做免费软件就有义务去解决他们的问题或者实现他们的需求，所以挺生气的。
> 这位老哥在之前issue中的言论是否正确已经无所谓了，毕竟我又不是程序或者产品，需求又不用我去实现。但如果真的想评价谁或言论，希望还是先把上一个issue看完。
> 再次抱歉。

建议去看一下。到底是

> 请不要污染 389 名 watcher 的邮箱。**开源项目 issue 区不是你公开泄粪的场所。**
> 
> **开源项目 issue 区不是你公开泄粪的场所。**
> 
> 都已经是社会人了，行为举止连最基本的素质和礼貌都没有。**人间之屑**，你悔改罢

我被人咬了，然后是我的不对。他衣服道貌岸然的样子。所以就让我悔改。你么这些389名人可真厉害。

**Comment by luern0313** [comment]
我觉得没有一个开源作者，能容忍其它人因为不满足自己的需求，而骂这个项目“什么破玩意”
因为我有类似的经历，所以有些生气
这不是道德岸然，这只是对开源作者和开源项目基本的尊重而已

**Comment by ghost** [comment]
> 我觉得没有一个开源作者，能容忍其它人因为不满足自己的需求，而骂这个项目“什么破玩意”
> 因为我有类似的经历，所以有些生气
> 这不是道德岸然，这只是对开源作者和开源项目基本的尊重而已

不想跟你在bb下去了。自己玻璃心，非要不停的要人，还在这里继续。上来就被你喷了也是倒霉。

**Comment by ghost** [comment]
> 我觉得没有一个开源作者，能容忍其它人因为不满足自己的需求，而骂这个项目“什么破玩意”
> 因为我有类似的经历，所以有些生气
> 这不是道德岸然，这只是对开源作者和开源项目基本的尊重而已

说了八百六十遍了，我从来没让你满足我什么需求。都是你自己以为的。你真的有问题

**Comment by woshixuwenqi** [comment]
大家好 我事东北石油大学的许文奇 去年毕业的，，，我头像事我姥爷 他帅吧！！！！！！
我老家是辽宁朝阳赵家沟小卡图的 我的曾爷爷许步春之前迁居到黑龙江哈尔滨依兰县三道岗镇了，，，

我为什么这么牛逼呢，，，
因为我的太爷爷许魁在文革时期当过官 厉害把 他还把我家的族谱烧了，，，所以我现在一直在找爹，，，

喜欢我的请加我的wx myjjhuge，，，

**Comment by woshixuwenqi** [comment]
我有bat的Android源码，经过这个项目，面试了美团和知乎，在Android方面的知识过关很容易。拿到offer很轻松。我就是凭借着这个项目成为了猎头之间抢手的一员。如果你想提升自己，想面试轻松的通过。可以找我。很简单。
我是真的急缺钱了，我现在手头只有我做过的项目，另外我也可以收徒，Android开发。bat经历，教个学还是可以的。关于源码，我签过保密协议的，实在是急缺钱铤而走险。可以联系我我会给你看的，保密协议都是公司一份自己一份。那些连bat都不知道什么意思的，你们可以走了。

**Comment by woshixuwenqi** [comment]
各公司HR请注意：东北石油大学，2017届软件工程，许文奇，可能有违反贵司保密协议行为。证据已搜集并已archive。

https://github.com/woshixuwenqi/zhengju/tree/master

**Comment by woshixuwenqi** [comment]
大兄弟，咱这都东北人，老哥来给你唠嗑一下，你现在删贴，已经晚了

**Comment by ghost** [comment]
> 
> 
> 大兄弟，咱这都东北人，老哥来给你唠嗑一下，你现在删贴，已经晚了

明明是你先来骂我的。骂不过我，然后就扒了另一个人的隐私。

**Comment by undefinedor** [comment]
= = 贵issue已出名，围观中。。

**Comment by NeverBehave** [comment]
> > 大兄弟，咱这都东北人，老哥来给你唠嗑一下，你现在删贴，已经晚了
> 
> 明明是你先来骂我的。骂不过我，然后就扒了另一个人的隐私。

@WenCheese 

那你删除干嘛……大义凌然“保护”他人隐私？（他自己 Fork 了一份仓库尝试在自己仓库删除……）
https://github.com/WenCheese/zhengju/commit/78477cdcb5dafd4c5b8043ad6e80eb05bdb2148a

**Comment by ghost** [comment]
各位实在抱歉。事情发生的时候。头脑是热的。发生之后才知道自己的不对，于是我找到了luern。本来我就比luern大。但是我却没有控制住自己，提一个issue之后还要多人，是我不对。我们已经互加QQ，互相道过谦了，我们谈了很多已经释怀了。自己无论发生什么事都不能影响别人，让别人和你一起心情不好。是我错了，给大家带来了很大的不便。实在是抱歉。

**Comment by ghost** [comment]
提的issue也是有问题。不该说这个库垃圾，因为别人开放一个库，供你学习，已经仁至义尽。还要说人家。对弹幕库的开发者诚挚的道歉。

**Comment by berryboy2012** [comment]
Issue not relevant to this repo, suggest closing.

**Comment by luern0313** [comment]
我也再来道个歉，的确人在不理智的时候，做出的事情大多都是有问题的。刚开始不清楚issue的机制，提示收到30多封邮件的时候，已经是那个issue被锁之后了，这才意识到回复issue也会给watcher发邮件。各位都是搞技术的，大多都有不错的工作和事业，我刚上大学，各位是我以后的目标和榜样，来github本应和人学习，但给各位和开发者添了麻烦，实在是抱歉，请各位把这个就当作一个笑话吧，我的不成熟让各位见笑了。
祝各位事业顺利，身体健康，事事顺利
