### ISSUE TITLE
64位ndkbitmap so提供

### ISSUE THREAD

**Issue by lixian5968** [Bilibili/DanmakuFlameMaster#418]
大佬 打扰下，从 2019 年 8 月 1 日开始，在 Google Play 上发布的应用必须支持 64 位架构。
https://developer.android.google.cn/distribute/best-practices/develop/64-bit
有提供com.github.ctiao:ndkbitmap-armv8a:0.9.21 的计划吗？

**Comment by xinledanding** [comment]
对呀很着急呀

**Comment by wrh0313** [comment]
是不是没在维护了？

**Comment by lixian5968** [comment]
源码有写，只有在32位上加载so，应该不需要导入了
NativeBitmapFactory 
 public static void loadLibs() {
        if (notLoadAgain) {
            return;
        }
        if (!(DeviceUtils.isRealARMArch() || DeviceUtils.isRealX86Arch())) {
            notLoadAgain = true;
            nativeLibLoaded = false;
            return;
        }
        if (nativeLibLoaded) {
            return;
        }
