### ISSUE TITLE
建议增加弾幕行限制

### ISSUE THREAD

**Issue by over140** [Bilibili/DanmakuFlameMaster#68]
现在DanmakuGlobalConfig只能限制同屏弹幕数量，想固定在顶部或底部显示2-3行的弾幕，以便不影响观看体验

**Comment by ctiao** [comment]
嗯，可以做 ，再加个DanmakuFilter

**Comment by DukeLee1989** [comment]
这个功能有时间能**实现**吗？？？谢谢了。。

**Comment by ctiao** [comment]
https://github.com/Bilibili/DanmakuFlameMaster/commit/5ab69f6995c9d0766cccaea660603852b9a3f6ed

增加了控制行数和防重叠功能
