### ISSUE TITLE
弹幕池能否支持视频播放的变速功能？

### ISSUE THREAD

**Issue by hllai** [Bilibili/DanmakuFlameMaster#85]
由于视频支持变速功能（变快或变慢），所以原本40分钟才能播放完毕的视频，经过变速后，只需要20分钟就能播放完 了，但是在取弹幕的时候就发现弹幕的播放速度和获取速度没有变化，导致弹幕的内容不在原本之前发生弹幕的视频时间点出现。

**Comment by hllai** [comment]
能不能做到动态修改获取弹幕的速度倍数（相对于正常速度的倍数）。

**Comment by xqq** [comment]
需要修改Timer机制
这边三倍速视频也有这个问题。在计划中，近期没空实现

**Comment by hllai** [comment]
你能把大概要修改那些地方说下嘛？我想去研究研究下。

**Comment by xqq** [comment]
DrawHandler中的timer
目前的timer是以三次元时间System.currMilliseconds()为基准的
要想适应时钟不标准的视频，timer需要设定一个二次元时间基准，并由DFM外部来更新

**Comment by ctiao** [comment]
Callback回调中有个public void updateTimer(DanmakuTimer timer) 回调
可以在这里直接修改弹幕内部的timer, 可以从这里入手 ，类似这样：
```
        mDanmakuView.setCallback(new Callback() {

            @Override
            public void updateTimer(DanmakuTimer timer) {
                timer.add(timer.lastInterval() * 2); // 2倍速,请检查timer.lastInterval()值的范围是否正常
            }

            @Override
            public void prepared() {
                mDanmakuView.start();
            }
        });
```
（代码和思路未经测试，不知道存在什么问题）

**Comment by DorisGM** [comment]
> 能不能做到动态修改获取弹幕的速度倍数（相对于正常速度的倍数）。

请问你是否已经实现了？

**Comment by fengyang221** [comment]
我来说下现在暂时的解决方案和其他路线的坑。
1. mDanmakuView.setCallback的updateTimer里面，无论是使用timer.add还是timer.update，效果都不是很好，弹幕会卡顿，应该是弹幕内部的时间流与你外部强行更改时间流，造成两者反复拉扯。
2. 重写timer的add方法，也行不通，效果与1差不多，两者反复拉扯造成弹幕卡顿。

所以，最终方案只有一个，修改弹幕数据的本身的时间线，我用了下，效果很好，0.5倍速，1倍速，2倍速，都没任何问题。我重写了弹幕解析器，一旦切换倍速，弹幕要整体重置，parse方法里面对弹幕数据的时间线做修改。要注意的是，视频seek的时候，弹幕也要跟随seek，seekTo(当前视频时间点 / 倍速速率)。
