### ISSUE TITLE
请问如何同屏幕显示多行弹幕？

### ISSUE THREAD

**Issue by zhucheng2015** [Bilibili/DanmakuFlameMaster#86]
请问如何同屏幕显示多行弹幕？目前的效果是两行

**Comment by ctiao** [comment]
换行符是按B站的格式来的，换行符是/n，不是\n

**Comment by brucetoo** [comment]
DanmakuGlobalConfig.DEFAULT.setDanmakuStyle(DanmakuGlobalConfig.DANMAKU_STYLE_STROKEN, 3).setMaximumVisibleSizeInScreen(3); 

请问这个setMaximumVisibleSizeInScreen 意思是弹幕只能是3行 ？为什么我设置了这个弹幕多得时候还是会满屏，针对的情况是addDanmaku()的情况，非解析xml.
