### ISSUE TITLE
关于comment中属性的意思

### ISSUE THREAD

**Issue by a1052624849** [Bilibili/DanmakuFlameMaster#88]
我想从后台中提供comment的流内容，comment中p之后的内容不太懂什么意思。。代码追着看到了handler,感觉有点消化不了，毕业设计是android上的弹幕客户端，实在没办法想请教一下，感谢。。

**Comment by a1052624849** [comment]
其实主要就是comment的配置格式看不懂，我想先直接用这个项目把毕业设计做了再慢慢学习

**Comment by xqq** [comment]
https://github.com/Bilibili/DanmakuFlameMaster/blob/master/DanmakuFlameMaster/src/main/java/master/flame/danmaku/danmaku/parser/android/BiliDanmukuParser.java#L105

**Comment by a1052624849** [comment]
谢谢，谢谢，我要学的还多啊！
