### ISSUE TITLE
请问 支持图片显示吗

### ISSUE THREAD

**Issue by 283076875** [Bilibili/DanmakuFlameMaster#91]
是否支持图片显示呢，如果支持要如何设置。

**Comment by 283076875** [comment]
看了一下 之前几个人问答 ，StaticLayout 在包里没找到

**Comment by ctiao** [comment]
http://developer.android.com/reference/android/text/StaticLayout.html

**Comment by 283076875** [comment]
为什么主线不换成支持 带图片的，为了效率？

**Comment by bbcallen** [comment]
bilibili 本身并没有图片弹幕功能，所以暂时不考虑支持。
如果你有兴趣实现的话，欢迎 pull request.

**Comment by 283076875** [comment]
如果主线更新了 我们这边也要做一些修改，不能自动引入，谢啦
