### ISSUE TITLE
如何指定单屏幕中弹幕的行数？

### ISSUE THREAD

**Issue by brucetoo** [Bilibili/DanmakuFlameMaster#95]
DanmakuGlobalConfig.DEFAULT.setDanmakuStyle(DanmakuGlobalConfig.DANMAKU_STYLE_STROKEN, 3).setMaximumVisibleSizeInScreen(3);

请问这个setMaximumVisibleSizeInScreen 意思是弹幕只能是3行 ？为什么我设置了这个，弹幕多的时候还是会满屏，针对的情况是addDanmaku()的情况，非解析xml.

**Comment by ctiao** [comment]
setMaximumVisibleSizeInScreen是指设置弹幕密度，并不能精确控制行数
addDanmaku的时候不要设置这条弹幕的priority,否则会跳过filter，导致弹幕密度设置无法生效

**Comment by brucetoo** [comment]
您好，意思是现在还没支持 控制行数？只能按照addDanmaku的时间来绘制不同的行数？

**Comment by ctiao** [comment]
https://github.com/Bilibili/DanmakuFlameMaster/blob/master/DanmakuFlameMaster/src/main/java/master/flame/danmaku/danmaku/renderer/android/DanmakuRenderer.java#L64
弹幕密度的意思是限制一屏最多能出现一定数量的弹幕，如果你addDanmaku的时候设置了弹幕的priority，会认为这条弹幕需要跳过过滤设置(见上链接)，这样就会使这条弹幕直接显示出来,使弹幕密度限制无效。
控制行数可以通过修改DanmakuView的高度达到目的,
如果你说的是到达到一定行数，超过行数的弹幕就不显示的效果的话，暂时没有提供这个设置，欢迎提交修改后的pull request

**Comment by brucetoo** [comment]
好的，谢谢您的回答，如果您说的方法不能达到我使用目的，我更改源码后会pull request，谢谢

**Comment by brucetoo** [comment]
朋友 我再问下，为什么全局配置 setFBDanmakuVisibility （true） 弹幕还是显示在顶部？

**Comment by ctiao** [comment]
setFBDanmakuVisibility是设置底端类型的弹幕是否显示

**Comment by brucetoo** [comment]
BaseDanmaku 这个中好像没有初始化 弹幕是在上还是下显示的参数耶 ？

**Comment by brucetoo** [comment]
我错了 请忽略我。。麻烦了

**Comment by ctiao** [comment]
BaseDanmaku是abstract类，所有类型弹幕都是扩展这个类，根据弹幕类型的不同，会有不同的排版效果  
R2LDanmaku  是从右至左的滚动弹幕
L2RDanmaku  是从左至右的滚动弹幕
FBDanmaku  是固定在底端的弹幕
FTDanmaku  是固定在顶端的弹幕
SpecialDanmaku 是各种动画效果运动的弹幕

如果你需要实现一个自定义排版的弹幕类型，需要:
1.扩展BaseDanmaku实现一个新的弹幕类型,实现BaseDanmaku的几个抽象方法
2. DanmakuRetainer里实现排版的算法
3. DanmakuFactory.create里实现新类型弹幕的实例化创建

**Comment by brucetoo** [comment]
现在发现一个问题:在布局中定义了DanmakuView的高度后，能实现控制弹幕的行数目的，但是单位时间内弹幕很多时，会出现弹幕绘制重叠的问题，请问这个怎么处理。 我在addDanmaku的时候没有设置 priority,并且setMaximumVisibleSizeInScreen(5)。

**Comment by ctiao** [comment]
https://github.com/Bilibili/DanmakuFlameMaster/blob/e7b4848a07942f59fa3b5585d290fdf19fe62929/DanmakuFlameMaster/src/main/java/master/flame/danmaku/controller/DanmakuFilters.java#L92-L150
这应该算是一直存在的一个密度排布算法的优化问题，可以尝试微调这部分的代码，使弹幕密度分布的更均匀一些  ，或者等我调整这块代码。

**Comment by brucetoo** [comment]
恩恩 好的，Thank U , 我先试着调下，您优化后@ 下我哦。谢谢

**Comment by ctiao** [comment]
https://github.com/Bilibili/DanmakuFlameMaster/commit/5ab69f6995c9d0766cccaea660603852b9a3f6ed

增加了控制行数和防重叠功能

**Comment by kmfish** [comment]
@ctiao 

> 如果你需要实现一个自定义排版的弹幕类型，需要:
1.扩展BaseDanmaku实现一个新的弹幕类型,实现BaseDanmaku的几个抽象方法
> 2. DanmakuRetainer里实现排版的算法
> 3. DanmakuFactory.create里实现新类型弹幕的实例化创建

如果按这样来自定义排版的话，就得修改源码了，我是想不用去改动到源码，可以直接由使用者去扩展即可。我看你有提到要开放自定义布局的接口，现在有进展吗？
