### ISSUE TITLE
弹幕限制在屏幕的中间或者底部显示（行数也可以自定义控制），这个该怎么实现好啊？？

### ISSUE THREAD

**Issue by DukeLee1989** [Bilibili/DanmakuFlameMaster#96]

**Comment by ctiao** [comment]
新增一个弹幕类型，  在DanmakuRetainer里新增这个类型弹幕的排版算法
行数限制可以参考DanmakuFilter的做法

**Comment by DukeLee1989** [comment]
谢谢！！！好的，我试试。。。如果遇到问题再向您请教。

**Comment by ctiao** [comment]
https://github.com/Bilibili/DanmakuFlameMaster/commit/5ab69f6995c9d0766cccaea660603852b9a3f6ed

增加了控制行数和防重叠功能
